config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => 'omniauth_callbacks' }
  resources :users, only: [:update]
  resources :lists, except: [:index] do
    resources :items, only: [:create, :destroy] do
      resources :checkeds , only: [:create, :destroy]
      collection do 
        delete :destroy_all
      end
    end 
  end 
   
  root "welcome#index"
end

app/models/list.rb
class List < ActiveRecord::Base
  belongs_to :user
  has_many :items, dependent: :destroy

  # List must have a title and a description.
  validates :title, presence: true
  validates :description, presence: true
  # Validates the uniqueness of a user id so that User can only have one list with a cystom validation to create our own error message.
  validates :user_id, uniqueness: { value: true , message: "there can be only one! 'The Highlander will now chop your head off.'" }
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  helper_method :sort_column, :sort_direction

  def show
    @list = List.find(params[:id])
    @items = @list.items.order(sort_column + " " + sort_direction)
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    @list.update(user_id: current_user.id)
    if @list.save
      flash[:notice] = "List was successfully created."
      redirect_to @list
    else
      flash[:error] = "There was an error creating the list. Please try again!"
      render :new
    end
  end

  def edit
    @list = List.find(params[:id])
  end

  def update
    @list = List.find(params[:id])

    if @list.update(list_params)
      flash[:notice] = "List was successfully edited."
      redirect_to @list
    else
      flash[:error] = "There was a problem edited the list. Please try again."
      render :edit
    end
  end

  def destroy
    @list = List.find(params[:id])
    title = @list.title
    if @list.destroy
      flash[:notice] = "\"#{title}\" was deleted"
      redirect_to root_path
    else
      flash[:error] = "There was an error deleting your list. Please try again."
      render :show
    end
  end

  private

  def list_params
    params.require(:list).permit(:title, :description)
  end

  def sort_column
    Item.column_names.include?(params[:sort]) ? params[:sort] : "created_at" 
  end

  def sort_direction
   ["asc", "desc"].include?(params[:direction]) ? params[:direction] : "asc"
  end

end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/lists/edit.html.erb
<div class="row">
  <div class="col-md-2">
  </div>
  <div class="col-md-8">
  <%= form_for @list do |f| %>
    <% if @list.errors.any? %>
      <div class="alert alert-warning alert-dismissable">
        <button type="button" class="close" data-dismiss="alert" ><span>&times;</span></button> 
        <h4>There are <%= pluralize(@list.errors.count, 'error') %></h4>
        <ul>
          <% @list.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <div class="form-group">
      <%= f.label :title %>
      <%= f.text_field :title, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :description %>
      <%= f.text_area :description, rows: 8, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.submit "Update", class: "btn btn-info btn-lg" %>
    </div>
  <% end %>
  </div>
</div>

app/views/lists/new.html.erb
<div class="row">
  <div class="col-md-2">
  </div>
  <div class="col-md-8">
  <%= form_for @list do |f| %>
    <% if @list.errors.any? %>
      <div class="alert alert-warning alert-dismissable">
        <button type="button" class="close" data-dismiss="alert" ><span>&times;</span></button> 
        <h4>There are <%= pluralize(@list.errors.count, 'error') %></h4>
        <ul>
          <% @list.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <div class="form-group">
      <%= f.label :title %>
      <%= f.text_field :title, class: "form-control",  auto_complete: "off", placeholder: "Please give ToDo list a title" %>
    </div>
    <div class="form-group">
      <%= f.label :description %>
      <%= f.text_area :description, rows: 8, class: "form-control",  auto_complete: "off", placeholder: "Please give your list a description" %>
    </div>
    <div class="form-group">
      <%= f.submit "Create new list", class: "btn btn-info btn-lg" %>
    </div>
  <% end %>
  </div>
</div>

app/views/lists/show.html.erb
<h3 class="dashboard">My dashboard</h3>
<div class="jumbotron jumbotron-list">
  <div>
    <h2><b>List Name: </b></br><%= link_to @list.title, edit_list_path(@list) %></h2>
    <h2 class="lead"><b>Description:</b><%=  markdown @list.description %></h2>
  </div>
  <div class="row input-bar">
    <div class="col-md-12 new-item">
      <%= render partial: 'items/form', locals: { list: @list, item: @list.items.build } %>
    </div>
  </div>
</div>

  <div class="panel panel-default">
    <div class="col-md-12 panel-heading">
      <div class="col-md-1 panel-title">
        <h5>Check</h5>
      </div>
      <div class="col-md-7 panel-title">
        <h5>ToDo List Task</h5>
      </div>
      <div class="col-md-2 panel-title">
        <h5 class="sortable "><span class='pull-left'>Days left</span><%= sortable "created_at", " " %></h5>
      </div>
      <div class="col-md-2 panel-title">
        <h5>Actions</h5>
      </div>
    </div> 
    <div class="panel-body">
      <div class="js-list">
        <%= render @items %>  
      </div>           
    </div>  
    <div class="panel-footer">
      <div class="pull-left">
        <p>
          <%= link_to destroy_all_list_items_path(@list), class: "btn btn-warning btn-md", method: :delete do %> 
            <span>Clear List?</span>
          <% end %> 
        </p>
      </div>
      <div class="pull-right">
        <p>
          <%= link_to @list, method: :delete, data: { confirm: "Are you sure you want yo delete this list?" }, class: "btn btn-danger btn-md" do %> 
            <span>Delete List?</span>
          <% end %> 
        </p>
      </div>   
    </div>
  </div>